# Application Settings
application_settings:
  threads: 10 # for all modules except <<farm>>
  cpu_thread_count: 1 # for <<farm>> module
  database_url: "sqlite://./database.sqlite3" # sqlite or postgres
  skip_logged_accounts: true
  shuffle_accounts: true

# Attempts and Delay Settings
attempts_and_delay_settings:
  error_delay: 5
  delay_before_start: # delay for every node/account before starting the process
    min: 0 # seconds
    max: 0 # seconds

  delay_between_verification_nodes: # delay between verification nodes (IP score)
    min: 10 # minutes
    max: 30 # minutes

  max_register_attempts: 3
  max_login_attempts: 3
  max_stats_attempts: 3
  max_proxy_change_attempts: 2
  max_connect_wallet_attempts: 3
  max_verification_nodes_attempts: 3

  max_websocket_connect_attempts: 10
  delay_after_websocket_connect_attempts: # if all websocket connect attempts failed you can set delay before next cycle of attempts
    min: 300 # seconds
    max: 600 # seconds

# Nodes Settings
nodes_settings:
  enable_nodes_verification: false

  active_nodes_per_account:
    min: 30
    max: 30

  min_proxy_score: 50 # positive number from 1 to 100, if proxy score is less than this value, the node proxy will be changed

# Login Settings
login_settings:
  auth_by: "email" # password or email


# Captcha Settings
captcha_settings:
  two_captcha_api_key: ""
  anti_captcha_api_key: ""
  capsolver_api_key: ""

  captcha_service: "capsolver" # 2captcha, anticaptcha, capsolver


# Redirect Settings
redirect_settings:
  enable: false
  email: ""
  password: ""
  imap_server: ""

# IMAP Settings
imap_settings:
  use_proxy_for_imap: false
  use_single_imap:
    enable: false
    imap_server: "imap.gmx.net"

  servers:
    gmail.com: imap.gmail.com
    yahoo.com: imap.mail.yahoo.com
    icloud.com: imap.mail.me.com
    mail.ru: imap.mail.ru
    rambler.ru: imap.rambler.ru
    gmx.com: imap.gmx.com
    gmx.net: imap.gmx.net
    gmx.de: imap.gmx.net
    onet.pl: imap.poczta.onet.pl
    onet.com.pl: imap.poczta.onet.pl
    op.pl: imap.poczta.onet.pl
    proton.me: proton.imap.com